import { defineConfig } from "drizzle-kit"

/**
 * Drizzle Kit configuration (W7 — D1: Drizzle ORM + postgres.js client).
 *
 * The schema is generated by `drizzle-kit pull` (introspection) from the live
 * dev Postgres, whose canonical DDL is the SQL in `supabase/migrations/*.sql`.
 * Set DATABASE_URL before running drizzle-kit commands, e.g.:
 *   DATABASE_URL=postgresql://gwth:devpass@localhost:5443/gwth_v2 npx drizzle-kit pull
 */
export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
})
