// GENERATED by `drizzle-kit pull` from the dev Postgres (canonical DDL:
// supabase/migrations/*.sql), then HAND-PATCHED for drizzle-kit 0.31.10
// codegen bugs + the W11 Better Auth migration — RE-APPLY these after any
// future re-pull:
//   1. Empty-string column defaults were emitted as `.default(')` (unterminated
//      string); fixed to `.default("")` (9 columns).
//   2. W11 (Better Auth): the canonical user table is now `public."user"` (text
//      ids; see ../src/db/auth-schema.ts), NOT the old Supabase `auth.users`.
//      The six user-scoped FK columns (lessonProgress.userId, userAccess.userId,
//      betaAccessGrants.userId, newsVotes.userId, newsComments.userId,
//      credentialVerifications.userId) are `text` and reference `user.id`. The
//      hand-declared `usersInAuth`/`users` (auth.users) table has been removed.
import { pgTable, index, foreignKey, pgPolicy, check, uuid, text, integer, timestamp, boolean, unique, real, jsonb, pgView, doublePrecision } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"
// W11: the Better Auth `user` table (public."user", text ids) is now the FK
// target for every user-scoped column below.
import { user } from "../src/db/auth-schema"

export const lessonResources = pgTable("lesson_resources", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	lessonId: text("lesson_id").notNull(),
	title: text().notNull(),
	url: text().notNull(),
	type: text().default('link').notNull(),
	order: integer().default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_lesson_resources_lesson").using("btree", table.lessonId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.lessonId],
			foreignColumns: [lessons.id],
			name: "lesson_resources_lesson_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Service role manages resources", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Public can read resources", { as: "permissive", for: "select", to: ["public"] }),
	check("lesson_resources_type_check", sql`type = ANY (ARRAY['link'::text, 'download'::text, 'video'::text, 'article'::text])`),
]);

export const sections = pgTable("sections", {
	id: text().primaryKey().notNull(),
	courseId: text("course_id").notNull(),
	title: text().notNull(),
	order: integer().default(0).notNull(),
	month: integer().notNull(),
	isOptional: boolean("is_optional").default(false).notNull(),
	optionalTrack: text("optional_track"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_sections_course").using("btree", table.courseId.asc().nullsLast().op("text_ops")),
	index("idx_sections_month").using("btree", table.month.asc().nullsLast().op("int4_ops")),
	index("idx_sections_order").using("btree", table.order.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.courseId],
			foreignColumns: [courses.id],
			name: "sections_course_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Service role manages sections", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Public can read sections", { as: "permissive", for: "select", to: ["public"] }),
	check("sections_month_check", sql`month = ANY (ARRAY[1, 2, 3])`),
]);

export const lessons = pgTable("lessons", {
	id: text().primaryKey().notNull(),
	slug: text().notNull(),
	title: text().notNull(),
	description: text().default("").notNull(),
	order: integer().default(0).notNull(),
	duration: integer().default(45).notNull(),
	difficulty: text().default('beginner').notNull(),
	category: text().default("").notNull(),
	sectionId: text("section_id").notNull(),
	courseId: text("course_id").notNull(),
	courseSlug: text("course_slug").default('applied-ai-skills').notNull(),
	month: integer().notNull(),
	isOptional: boolean("is_optional").default(false).notNull(),
	optionalTrack: text("optional_track"),
	introVideoUrl: text("intro_video_url"),
	learnContent: text("learn_content").default("").notNull(),
	audioFileUrl: text("audio_file_url"),
	audioDuration: real("audio_duration"),
	buildVideoUrl: text("build_video_url"),
	buildInstructions: text("build_instructions"),
	status: text().default('available').notNull(),
	objectives: text().array().default([""]),
	tags: text().array().default([""]),
	prerequisites: text().array().default([""]),
	pipelineId: uuid("pipeline_id"),
	pipelineStatus: text("pipeline_status"),
	exportedAt: timestamp("exported_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_lessons_course").using("btree", table.courseId.asc().nullsLast().op("text_ops")),
	index("idx_lessons_month").using("btree", table.month.asc().nullsLast().op("int4_ops")),
	index("idx_lessons_order").using("btree", table.order.asc().nullsLast().op("int4_ops")),
	index("idx_lessons_section").using("btree", table.sectionId.asc().nullsLast().op("text_ops")),
	index("idx_lessons_slug").using("btree", table.slug.asc().nullsLast().op("text_ops")),
	index("idx_lessons_tags").using("gin", table.tags.asc().nullsLast().op("array_ops")),
	foreignKey({
			columns: [table.courseId],
			foreignColumns: [courses.id],
			name: "lessons_course_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.sectionId],
			foreignColumns: [sections.id],
			name: "lessons_section_id_fkey"
		}).onDelete("cascade"),
	unique("lessons_slug_key").on(table.slug),
	pgPolicy("Service role manages lessons", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Public can read lessons", { as: "permissive", for: "select", to: ["public"] }),
	check("lessons_difficulty_check", sql`difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])`),
	check("lessons_month_check", sql`month = ANY (ARRAY[1, 2, 3])`),
	check("lessons_status_check", sql`status = ANY (ARRAY['locked'::text, 'available'::text, 'in-progress'::text, 'completed'::text])`),
	check("lessons_pipeline_status_check", sql`pipeline_status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'review'::text, 'published'::text, 'exported'::text])`),
]);

export const quizQuestions = pgTable("quiz_questions", {
	id: text().primaryKey().notNull(),
	lessonId: text("lesson_id").notNull(),
	question: text().notNull(),
	options: text().array().default([""]).notNull(),
	correctOptionIndex: integer("correct_option_index").default(0).notNull(),
	explanation: text().default("").notNull(),
	order: integer().default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_quiz_questions_lesson").using("btree", table.lessonId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.lessonId],
			foreignColumns: [lessons.id],
			name: "quiz_questions_lesson_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Service role manages quiz questions", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Public can read quiz questions", { as: "permissive", for: "select", to: ["public"] }),
]);

export const courses = pgTable("courses", {
	id: text().primaryKey().notNull(),
	slug: text().notNull(),
	title: text().notNull(),
	description: text().default("").notNull(),
	thumbnail: text(),
	blurDataUrl: text("blur_data_url"),
	price: integer().default(0).notNull(),
	category: text().default('Applied AI').notNull(),
	difficulty: text().default('beginner').notNull(),
	estimatedDuration: integer("estimated_duration").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("courses_slug_key").on(table.slug),
	pgPolicy("Service role manages courses", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Public can read courses", { as: "permissive", for: "select", to: ["public"] }),
	check("courses_difficulty_check", sql`difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])`),
]);

// W3 — labs content table. Mirrors the `Lab` shape consumed by
// src/lib/data/labs.ts (instructions = LabStep[] stored as jsonb). Hand-written
// (not pulled), so RE-DECLARE after any future `drizzle-kit pull`.
export const labs = pgTable("labs", {
	id: text().primaryKey().notNull(),
	slug: text().notNull(),
	title: text().notNull(),
	description: text().default("").notNull(),
	difficulty: text().default('beginner').notNull(),
	duration: integer().default(60).notNull(),
	technologies: text().array().default([]).notNull(),
	learningOutcomes: text("learning_outcomes").array().default([]).notNull(),
	prerequisites: text(),
	content: text().default("").notNull(),
	instructions: jsonb().default([]).notNull(),
	category: text().default("").notNull(),
	projectType: text("project_type").default("").notNull(),
	color: text().default("").notNull(),
	icon: text().default("").notNull(),
	image: text(),
	isPremium: boolean("is_premium").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_labs_slug").using("btree", table.slug.asc().nullsLast().op("text_ops")),
	index("idx_labs_category").using("btree", table.category.asc().nullsLast().op("text_ops")),
	unique("labs_slug_key").on(table.slug),
	check("labs_difficulty_check", sql`difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])`),
]);

export const newsArticles = pgTable("news_articles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	slug: text().notNull(),
	title: text().notNull(),
	excerpt: text().notNull(),
	content: text().notNull(),
	url: text(),
	category: text().default('ai-launch').notNull(),
	tags: text().array().default([""]),
	thumbnailUrl: text("thumbnail_url"),
	author: text().default('David').notNull(),
	voteCount: integer("vote_count").default(0).notNull(),
	commentCount: integer("comment_count").default(0).notNull(),
	labSlug: text("lab_slug"),
	isFeatured: boolean("is_featured").default(false).notNull(),
	status: text().default('published').notNull(),
	publishedAt: timestamp("published_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	reviewedByAdmin: boolean("reviewed_by_admin").default(false).notNull(),
}, (table) => [
	index("idx_news_articles_category").using("btree", table.category.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_published").using("btree", table.publishedAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_news_articles_slug").using("btree", table.slug.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_tags").using("gin", table.tags.asc().nullsLast().op("array_ops")),
	index("idx_news_articles_votes").using("btree", table.voteCount.desc().nullsFirst().op("int4_ops")),
	unique("news_articles_slug_key").on(table.slug),
	pgPolicy("Service role manages articles", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("Public can read published articles", { as: "permissive", for: "select", to: ["public"] }),
	check("news_articles_status_check", sql`status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])`),
]);

export const newsVotes = pgTable("news_votes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	articleId: uuid("article_id").notNull(),
	userId: text("user_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_news_votes_article").using("btree", table.articleId.asc().nullsLast().op("uuid_ops")),
	index("idx_news_votes_user").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.articleId],
			foreignColumns: [newsArticles.id],
			name: "news_votes_article_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "news_votes_user_id_fkey"
		}).onDelete("cascade"),
	unique("news_votes_article_id_user_id_key").on(table.userId, table.articleId),
	pgPolicy("Users can delete own votes", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = user_id)` }),
	pgPolicy("Authenticated users can insert own votes", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("Anyone can read votes", { as: "permissive", for: "select", to: ["public"] }),
]);

export const newsComments = pgTable("news_comments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	articleId: uuid("article_id").notNull(),
	userId: text("user_id").notNull(),
	parentId: uuid("parent_id"),
	body: text().notNull(),
	userName: text("user_name").default('Anonymous').notNull(),
	userAvatar: text("user_avatar"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_news_comments_article").using("btree", table.articleId.asc().nullsLast().op("uuid_ops")),
	index("idx_news_comments_parent").using("btree", table.parentId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.articleId],
			foreignColumns: [newsArticles.id],
			name: "news_comments_article_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.parentId],
			foreignColumns: [table.id],
			name: "news_comments_parent_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "news_comments_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Users can delete own comments", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = user_id)` }),
	pgPolicy("Authenticated users can insert own comments", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("Anyone can read comments", { as: "permissive", for: "select", to: ["public"] }),
]);

export const benchmarkRuns = pgTable("benchmark_runs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	runAt: timestamp("run_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	articlesSampled: integer("articles_sampled").default(0).notNull(),
	providersTested: integer("providers_tested").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_benchmark_runs_date").using("btree", table.runAt.desc().nullsFirst().op("timestamptz_ops")),
	pgPolicy("Public can read benchmark runs", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
	pgPolicy("Service role manages benchmark runs", { as: "permissive", for: "all", to: ["public"] }),
]);

export const benchmarkResults = pgTable("benchmark_results", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	runId: uuid("run_id").notNull(),
	articleTitle: text("article_title").notNull(),
	articleUrl: text("article_url").notNull(),
	providerId: text("provider_id").notNull(),
	providerName: text("provider_name").notNull(),
	model: text().notNull(),
	latencyMs: real("latency_ms").default(0).notNull(),
	success: boolean().default(false).notNull(),
	error: text().default(""),
	jsonValid: boolean("json_valid").default(false),
	fieldsComplete: boolean("fields_complete").default(false),
	importanceScore: integer("importance_score"),
	category: text().default(""),
	titleRewritten: text("title_rewritten").default(""),
	excerpt: text().default(""),
	contentLength: integer("content_length").default(0),
	estimatedInputTokens: integer("estimated_input_tokens").default(0),
	estimatedOutputTokens: integer("estimated_output_tokens").default(0),
	estimatedCostUsd: real("estimated_cost_usd").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_benchmark_results_provider").using("btree", table.providerId.asc().nullsLast().op("text_ops")),
	index("idx_benchmark_results_run").using("btree", table.runId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.runId],
			foreignColumns: [benchmarkRuns.id],
			name: "benchmark_results_run_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Public can read benchmark results", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
	pgPolicy("Service role manages benchmark results", { as: "permissive", for: "all", to: ["public"] }),
]);

export const stripeEvents = pgTable("stripe_events", {
	id: text().primaryKey().notNull(),
	type: text().notNull(),
	receivedAt: timestamp("received_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const userAccess = pgTable("user_access", {
	userId: text("user_id").primaryKey().notNull(),
	accessSource: text("access_source").default('registered').notNull(),
	subscriptionState: text("subscription_state").default('registered').notNull(),
	subscriptionMonth: integer("subscription_month").default(0).notNull(),
	validUntil: timestamp("valid_until", { withTimezone: true, mode: 'string' }),
	gracePeriodEnds: timestamp("grace_period_ends", { withTimezone: true, mode: 'string' }),
	lastPaymentAt: timestamp("last_payment_at", { withTimezone: true, mode: 'string' }),
	stripeCustomerId: text("stripe_customer_id"),
	stripeSubscriptionId: text("stripe_subscription_id"),
	stripePriceId: text("stripe_price_id"),
	stripeSubscriptionStatus: text("stripe_subscription_status"),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_user_access_stripe_customer_id").using("btree", table.stripeCustomerId.asc().nullsLast().op("text_ops")).where(sql`(stripe_customer_id IS NOT NULL)`),
	index("idx_user_access_stripe_subscription_id").using("btree", table.stripeSubscriptionId.asc().nullsLast().op("text_ops")).where(sql`(stripe_subscription_id IS NOT NULL)`),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "user_access_user_id_fkey"
		}).onDelete("cascade"),
	unique("user_access_stripe_customer_id_key").on(table.stripeCustomerId),
	unique("user_access_stripe_subscription_id_key").on(table.stripeSubscriptionId),
	pgPolicy("Users can read own access", { as: "permissive", for: "select", to: ["authenticated"], using: sql`(( SELECT auth.uid() AS uid) = user_id)` }),
	check("user_access_access_source_check", sql`access_source = ANY (ARRAY['registered'::text, 'manual_beta'::text, 'stripe_course'::text, 'stripe_ongoing'::text])`),
	check("user_access_subscription_state_check", sql`subscription_state = ANY (ARRAY['registered'::text, 'month1'::text, 'month2'::text, 'month3'::text, 'ongoing'::text, 'lapsed'::text])`),
	check("user_access_subscription_month_check", sql`(subscription_month >= 0) AND (subscription_month <= 3)`),
]);

export const lessonProgress = pgTable("lesson_progress", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: text("user_id").notNull(),
	lessonId: text("lesson_id").notNull(),
	isCompleted: boolean("is_completed").default(false).notNull(),
	progress: real().default(0).notNull(),
	quizScore: real("quiz_score"),
	bestQuizScore: real("best_quiz_score"),
	quizAttempts: integer("quiz_attempts").default(0).notNull(),
	timeSpent: integer("time_spent").default(0).notNull(),
	lastAccessedAt: timestamp("last_accessed_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: 'string' }),
	introVideoProgress: real("intro_video_progress").default(0).notNull(),
	quizPassed: boolean("quiz_passed").default(false).notNull(),
}, (table) => [
	index("idx_lesson_progress_lesson").using("btree", table.lessonId.asc().nullsLast().op("text_ops")),
	index("idx_lesson_progress_user").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "lesson_progress_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.lessonId],
			foreignColumns: [lessons.id],
			name: "lesson_progress_lesson_id_fkey"
		}).onDelete("cascade"),
	unique("lesson_progress_user_id_lesson_id_key").on(table.userId, table.lessonId),
	pgPolicy("Users update own progress", { as: "permissive", for: "update", to: ["public"], using: sql`(auth.uid() = user_id)` }),
	pgPolicy("Users insert own progress", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("Users read own progress", { as: "permissive", for: "select", to: ["public"] }),
	check("lesson_progress_progress_check", sql`(progress >= (0)::double precision) AND (progress <= (1)::double precision)`),
	check("lesson_progress_intro_video_progress_check", sql`(intro_video_progress >= (0)::double precision) AND (intro_video_progress <= (1)::double precision)`),
]);

export const credentialVerifications = pgTable("credential_verifications", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: text("user_id").notNull(),
	courseId: text("course_id").notNull(),
	verificationCode: text("verification_code").notNull(),
	isPublic: boolean("is_public").default(false).notNull(),
	learnerName: text("learner_name").notNull(),
	gwthScore: real("gwth_score").default(0).notNull(),
	percentileLabel: text("percentile_label").default('Building foundations').notNull(),
	trajectoryLabel: text("trajectory_label").default('In progress').notNull(),
	issuedAt: timestamp("issued_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_credential_verifications_code").using("btree", table.verificationCode.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.courseId],
			foreignColumns: [courses.id],
			name: "credential_verifications_course_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "credential_verifications_user_id_fkey"
		}).onDelete("cascade"),
	unique("credential_verifications_verification_code_key").on(table.verificationCode),
	unique("credential_verifications_user_id_course_id_key").on(table.userId, table.courseId),
	pgPolicy("Users can update own credential sharing", { as: "permissive", for: "update", to: ["authenticated"], using: sql`(( SELECT auth.uid() AS uid) = user_id)`, withCheck: sql`(( SELECT auth.uid() AS uid) = user_id)`  }),
	pgPolicy("Users can read own credentials", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Public can read shared credentials", { as: "permissive", for: "select", to: ["public"] }),
]);

export const newsbotRawArticles = pgTable("newsbot_raw_articles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	sourceName: text("source_name").notNull(),
	sourceUrl: text("source_url").notNull(),
	title: text().notNull(),
	contentSnippet: text("content_snippet"),
	author: text(),
	tags: text().array().default([""]),
	publishedAt: timestamp("published_at", { withTimezone: true, mode: 'string' }),
	fetchedAt: timestamp("fetched_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	processed: boolean().default(false),
	processingResult: jsonb("processing_result"),
	importanceScore: integer("importance_score").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_raw_articles_fetched").using("btree", table.fetchedAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_raw_articles_processed").using("btree", table.processed.asc().nullsLast().op("bool_ops")),
	index("idx_raw_articles_source").using("btree", table.sourceName.asc().nullsLast().op("text_ops")),
	unique("newsbot_raw_articles_source_url_key").on(table.sourceUrl),
	pgPolicy("Service role manages raw articles", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
]);

export const newsletterSubscribers = pgTable("newsletter_subscribers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	source: text().default('newsbot').notNull(),
	subscribedAt: timestamp("subscribed_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true, mode: 'string' }),
	isActive: boolean("is_active").default(true),
	mailerliteSubscriberId: text("mailerlite_subscriber_id"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_newsletter_active").using("btree", table.isActive.asc().nullsLast().op("bool_ops")),
	index("idx_newsletter_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	unique("newsletter_subscribers_email_key").on(table.email),
	pgPolicy("Service role manages subscribers", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
]);

export const waitlist = pgTable("waitlist", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	name: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_waitlist_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	unique("waitlist_email_key").on(table.email),
	pgPolicy("Service role can manage waitlist", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true`  }),
]);

export const betaAccessGrants = pgTable("beta_access_grants", {
	email: text().primaryKey().notNull(),
	userId: text("user_id"),
	subscriptionMonth: integer("subscription_month").default(3).notNull(),
	validUntil: timestamp("valid_until", { withTimezone: true, mode: 'string' }),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_beta_access_grants_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")).where(sql`(user_id IS NOT NULL)`),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "beta_access_grants_user_id_fkey"
		}).onDelete("set null"),
	check("beta_access_grants_subscription_month_check", sql`(subscription_month >= 1) AND (subscription_month <= 3)`),
	check("beta_access_grants_email_check", sql`email = lower(TRIM(BOTH FROM email))`),
]);

export const feedback = pgTable("feedback", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: text("user_id").notNull(),
	sourcePath: text("source_path").notNull(),
	category: text().default('general').notNull(),
	message: text().notNull(),
	userAgent: text("user_agent"),
	emailSent: boolean("email_sent").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_feedback_created_at").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_feedback_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "feedback_user_id_fkey"
		}).onDelete("cascade"),
	check("feedback_category_check", sql`category = ANY (ARRAY['bug'::text, 'content'::text, 'idea'::text, 'general'::text])`),
]);

export const newsArticlesRanked = pgView("news_articles_ranked", {	id: uuid(),
	slug: text(),
	title: text(),
	excerpt: text(),
	content: text(),
	url: text(),
	category: text(),
	tags: text(),
	thumbnailUrl: text("thumbnail_url"),
	author: text(),
	voteCount: integer("vote_count"),
	commentCount: integer("comment_count"),
	labSlug: text("lab_slug"),
	isFeatured: boolean("is_featured"),
	status: text(),
	publishedAt: timestamp("published_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }),
	hotnessScore: doublePrecision("hotness_score"),
}).as(sql`SELECT id, slug, title, excerpt, content, url, category, tags, thumbnail_url, author, vote_count, comment_count, lab_slug, is_featured, status, published_at, created_at, updated_at, CASE WHEN vote_count <= 1 THEN 0::double precision ELSE (vote_count - 1)::double precision / power(EXTRACT(epoch FROM now() - published_at) / 3600::numeric + 2::numeric, 1.8)::double precision END AS hotness_score FROM news_articles WHERE status = 'published'::text`);