/**
 * Drizzle schema for the GWTH website database (W7 — Phase 1 foundation).
 *
 * This file is the app-facing schema entry point referenced by drizzle.config.ts
 * (`schema: "./src/db/schema.ts"`). The actual table/view/relation definitions are
 * GENERATED by `drizzle-kit pull` (DB introspection) into `../../drizzle/`, whose
 * canonical source is the raw SQL in `supabase/migrations/*.sql`.
 *
 * Do NOT hand-edit the generated files. To refresh after a DDL change:
 *   DATABASE_URL=postgresql://gwth:devpass@localhost:5443/gwth_v2 npx drizzle-kit pull
 *
 * Re-exported here so app code can `import { ... } from "@/db/schema"`.
 */
export * from "../../drizzle/schema"
export * from "../../drizzle/relations"
