/**
 * Every visible string in the lessons-in-parts viewer, in one place so the
 * whole set can be read and checked together (gwth-public-writing skill).
 * No em or en dashes. British English.
 */
import type { LessonFormat } from "@/lib/lessons/parts"

export const FORMAT_COPY: Record<LessonFormat, { name: string; short: string; blurb: string; choose: string }> = {
  watch: {
    name: "Watch short videos",
    short: "Watch",
    blurb: "A short video for each part, with captions. The same text is underneath if you'd rather read it.",
    choose: "Choose Watch short videos",
  },
  read: {
    name: "Read or listen",
    short: "Read",
    blurb: "One part at a time. Read it yourself, or press Play to hear it read aloud while each word is highlighted.",
    choose: "Choose Read or listen",
  },
}

export const COPY = {
  backToCourse: "Back to the course",
  formatSwitchLabel: "How you take this lesson",
  choiceTitle: "How would you like to take your lessons?",
  choiceBody:
    "Try both below. You can change your mind at any time with the Watch and Read buttons at the top of every lesson, or in Settings.",
  playPreview: "Play preview",
  pausePreview: "Pause preview",
  hearIt: "Hear it",
  stopHearing: "Stop",
  lessonLine: (n: number, parts: number, minutes: number) => `Lesson ${n}. ${parts} parts, about ${minutes} minutes.`,
  inThisLesson: "In this lesson",
  introVideo: "Introduction video",
  start: "Start part 1",
  carryOn: (part: number) => `Carry on from part ${part}`,
  reviewEnd: "Go to the end of the lesson",
  partOf: (i: number, n: number) => `Part ${i} of ${n}`,
  minutes: (m: number) => `${m} min`,
  partsDone: (done: number, n: number) => `${done} of ${n} parts done`,
  done: "Done",
  youAreHere: "You are here",
  play: "Play",
  pause: "Pause",
  speed: "Speed",
  readAlong: "Read along",
  audioPosition: "Position in the audio",
  audioMissing: "The audio for this part is not ready yet.",
  readInstead: "Read this part instead",
  partVideo: (i: number) => `Part ${i} video`,
  checkLabel: "Check your understanding",
  tryAgain: "Have another go.",
  rightAnswer: "Right answer",
  notThisOne: "Not this one",
  theAnswer: (option: string) => `The answer is: ${option}`,
  readAgain: "Read that bit again",
  watchAgain: "Watch that bit again",
  answerFirst: "Answer the question to continue.",
  saving: "Checking your answer...",
  answerError: "Your answer could not be checked. Try again.",
  back: "Back",
  continue: "Continue",
  finish: "Finish the lesson",
  confused: "This part confused me",
  confusedNoted: "Thanks, noted",
  confusedAsk: "Thanks for telling us. What was confusing? (optional)",
  confusedLabel: "What was confusing? (optional)",
  listenAgain: "Listen to this part again",
  watchPartAgain: "Watch this part again",
  send: "Send",
  noteThanks: "Thanks, we have your note.",
  confusedThanks: "Thanks, we have noted that this part was confusing.",
  finishedTitle: "You have finished this lesson",
  finishedBody: "Every part is done.",
  finishedNextProject: "Every part is done. The project below puts it into practice.",
  ratingTitle: "How was this lesson?",
  ratings: [
    { value: "bad", label: "Bad" },
    { value: "fine", label: "Fine" },
    { value: "good", label: "Good" },
  ] as const,
  ratingMore: "Thanks. Want to tell us more?",
  ratingMoreLabel: "Want to tell us more?",
  noThanks: "No thanks",
  ratingThanks: "Thanks for rating this lesson.",
  dismiss: "Dismiss",
  projectTitle: "Next: the project",
  nextLesson: (title: string) => `Next lesson: ${title}`,
  notFinished: "Finish every part to complete this lesson.",
} as const
